name: Latest blog post workflow

on:
  schedule:
    - cron: '0 0 * * *' # Daily
  push:
    branches:
      - main

jobs:
  update-readme:
    name: Update blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/devmdrd"
